### ISSUE TITLE
As anything still using this?

### ISSUE THREAD

**Issue by dan-searle** [Financial-Times/grunt-origami-demoer#11]
Should we delete it or at least mark it as deprecated?

@wheresrhys @triblondon

**Comment by wheresrhys** [comment]
Good call. I think I've updated all mine to use obt, and if I missed any I'll update them in the next release. I'd be happy to have it deleted

**Comment by dan-searle** [comment]
Great. I've put a deprecation warning in the readme for now.

**Comment by dan-searle** [comment]
Also I've marked it as deprecated on npm.

**Comment by kaelig** [comment]
Looks like nobody has been using it for a long time.

Can somebody kill this repo and unregister the module from the npm registry?

**Comment by triblondon** [comment]
I think @wheresrhys has access to the npm account that published this.  I'm able to remove the repo when that's done.
